package br.com.f2e.ovenplatform.shared.infrastructure.web.exception;

public final class ApiErrorCodes {

  public static final String INVALID_ARGUMENT = "INVALID_ARGUMENT";
  public static final String VALIDATION_ERROR = "VALIDATION_ERROR";
  public static final String RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND";
  public static final String DUPLICATE_USER_EMAIL = "DUPLICATE_USER_EMAIL";
  public static final String TENANT_NOT_FOUND = "TENANT_NOT_FOUND";
  public static final String DATA_INTEGRITY_VIOLATION = "DATA_INTEGRITY_VIOLATION";
  public static final String MISSING_REQUEST_HEADER = "MISSING_REQUEST_HEADER";
  public static final String INVALID_API_VERSION = "INVALID_API_VERSION";
  public static final String INVALID_ORDER_STATUS_TRANSITION = "INVALID_ORDER_STATUS_TRANSITION";
  public static final String DUPLICATED_USER_TENANT = "DUPLICATED_USER_TENANT";
  public static final String INACTIVE_TENANT_MEMBERSHIP = "INACTIVE_TENANT_MEMBERSHIP";
  public static final String TENANT_ACCESS_DENIED = "TENANT_ACCESS_DENIED";
  public static final String TENANT_TEAM_MANAGEMENT_DENIED = "TENANT_TEAM_MANAGEMENT_DENIED";
  public static final String INVALID_TICKET_STATUS_TRANSITION = "INVALID_TICKET_STATUS_TRANSITION";
  public static final String IMAGE_UPLOAD_SIZE_EXCEEDED = "IMAGE_UPLOAD_SIZE_EXCEEDED";
  public static final String STORED_IMAGE_METADATA_MISMATCH = "STORED_IMAGE_METADATA_MISMATCH";
  public static final String STORED_IMAGE_NOT_AVAILABLE = "STORED_IMAGE_NOT_AVAILABLE";
  public static final String IMAGE_UPLOAD_NOT_FOUND = "IMAGE_UPLOAD_NOT_FOUND";
  public static final String PAYMENT_GATEWAY_OUTCOME_UNKNOWN = "PAYMENT_GATEWAY_OUTCOME_UNKNOWN";
  public static final String PAYMENT_GATEWAY_FAILURE = "PAYMENT_GATEWAY_FAILURE";
  public static final String INVALID_EXTERNAL_PAYMENT_ATTEMPT_STATUS_TRANSITION =
      "INVALID_EXTERNAL_PAYMENT_ATTEMPT_STATUS_TRANSITION";
  public static final String EXTERNAL_PAYMENT_ATTEMPT_NOT_ALLOWED =
      "EXTERNAL_PAYMENT_ATTEMPT_NOT_ALLOWED";
  public static final String EXTERNAL_PAYMENT_METHOD_NOT_ALLOWED =
      "EXTERNAL_PAYMENT_METHOD_NOT_ALLOWED";

  private ApiErrorCodes() {}
}
