spring:
  docker:
    compose:
      enabled: false
  jpa:
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

management:
  metrics:
    tags:
      environment: ${OVEN_ENVIRONMENT:staging}
  tracing:
    sampling:
      probability: ${OVEN_TRACING_SAMPLING_PROBABILITY:0.0}
    export:
      otlp:
        enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

oven:
  environment: staging

server:
  forward-headers-strategy: framework