spring:
  application:
    name: oven-platform
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:oven}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
  mvc:
    apiversion:
      default: 1.0
      supported: 1.0, 2.0
      use:
        header: X-API-Version